// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Gjallarhorn.Bindable.Avalonia")>]
[<assembly: AssemblyProductAttribute("Gjallarhorn.Bindable")>]
[<assembly: AssemblyDescriptionAttribute("Unidirectional Framework for XAML Platforms built on top of Gjallarhorn")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018 Reed Copsey, Jr.")>]
[<assembly: AssemblyCompanyAttribute("Reed Copsey, Jr.")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Gjallarhorn.Bindable.Avalonia"
    let [<Literal>] AssemblyProduct = "Gjallarhorn.Bindable"
    let [<Literal>] AssemblyDescription = "Unidirectional Framework for XAML Platforms built on top of Gjallarhorn"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyCopyright = "Copyright 2018 Reed Copsey, Jr."
    let [<Literal>] AssemblyCompany = "Reed Copsey, Jr."
